trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  functionAppName: 'playground-function-app'
  appPackagePath: '$(System.DefaultWorkingDirectory)'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: 'Azure/Functions/Functions.App/Functions.App.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'msdn-subscription(093dc2a0-5196-4c86-8889-f873e19b6789)'
    appType: 'functionAppLinux'
    appName: '$(functionAppName)'
    package: '$(Build.ArtifactStagingDirectory)'
    deploymentMethod: 'auto'